package com.huangliutan.crm.settings.mapper;

import com.huangliutan.crm.settings.domain.DicType;

import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 21:29:16 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 21:29:16 CST 2020
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 21:29:16 CST 2020
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 21:29:16 CST 2020
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 21:29:16 CST 2020
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 21:29:16 CST 2020
     */
    int updateByPrimaryKey(DicType record);

    /**
     * 查询所有的数据字典表数据
     * @return
     */
    List<DicType> selectAllDicTypes();

    /**
     * 根据主键查找数据字典表数据
     * @param code 主键
     * @return 数据字典映射类
     */
    DicType selectDicTypeByCode(String code);

    /**
     * 将数据保存到数据库
     * @param dicType
     * @return
     */
    int insertDicType(DicType dicType);

    /**
     * 删除数据字典类型
     * @param code
     * @return
     */
    int deleteDicTypeByCodes(String[] code);

    /**
     * 修改数据字典类型
     * @param dicType
     * @return
     */
    int updateDicType(DicType dicType);
}