package com.huangliutan.crm.settings.mapper;

import com.huangliutan.crm.settings.domain.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 15:17:41 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 15:17:41 CST 2020
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 15:17:41 CST 2020
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 15:17:41 CST 2020
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 15:17:41 CST 2020
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 15:17:41 CST 2020
     */
    int updateByPrimaryKey(DicValue record);

    /**
     * 查询所有的数据字典值
     * @return
     */
    List<DicValue> selectAllDicValues();

    /**
     * 保存数据字典值
     * @param dicValue
     * @return
     */
    int insertDicValue(DicValue dicValue);

    /**
     * 删除数据字典值
     * @param id
     * @return
     */
    int deleteDicValueByIds(String[] id);

    /**
     * 根据主键值id查询数据字典值
     * @param id
     * @return
     */
    DicValue selectDicValueById(String id);

    /**
     * 修改数据字典值
     * @param dicValue
     * @return
     */
    int updateDicValue(DicValue dicValue);

    /**
     * 根据typeCode删除数据字典值
     * @param code
     * @return
     */
    int deleteDicValueByTypeCodes(String[] code);

    /**
     *根据数据字典类型查询所有的数据字典值
     */
    List<DicValue> selectAllDicValueByTypeCode(String typeCode);

}