package com.huangliutan.crm.settings.mapper;

import com.huangliutan.crm.settings.domain.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat May 16 09:59:16 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat May 16 09:59:16 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat May 16 09:59:16 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat May 16 09:59:16 CST 2020
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat May 16 09:59:16 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat May 16 09:59:16 CST 2020
     */
    int updateByPrimaryKey(User record);

    /**
     * 该方法查询数据库用户信息
     * @param map 参数是map
     * @return 返回一个用户对象
     */
    User selectUserByLoginActAndPwd(Map<String,Object> map);

    /**
     * 查询所有状态激活的用户
     * @return
     */
    List<User> selectAllUsers();
}